### PR TITLE
added shutdown notification

### PR DESCRIPTION
**Pull request by CookieComputing**
No logging information for kube-janitor shutdowns running the `--once` argument or if suddenly shutdown.

### CODE REVIEW

**Comment by hjacobs** [comment]
Why do you need this log line?

**Comment by CookieComputing** [comment]
Looking at the logs of the container running `kube-janitor`, I thought it would be nice to have a clear indication of where the end of the run was at.

**Comment by hjacobs** [comment]
@CookieComputing yes, but that would mean that running `kube-janitor` as CronJob would always log this extra line (e.g. every minute or whatever interval the CronJob has). I think the added value is not so high to see this every X minutes (for the CronJob case)

**Comment by CookieComputing** [comment]
Fair point! I'll close this PR then.

**Pull request closed without merging**
