### PR TITLE
Add a feature that allows to set annotation "expire date"  

### PR DESCRIPTION
**Pull request by SongGithub**
This PR will address issue #6 

Addition includes:
- a helper function to parse datetime stamp string
- integrate the helper function to Janitor.py
- write unit tests for the addition
- update README.rst file about the addition.

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks for the PR! I would prefer to use the builtin tooling to parse the timestamp, i.e. use the same logic as here: https://github.com/hjacobs/kube-janitor/blob/master/kube_janitor/janitor.py#L36

**Comment by hjacobs** [comment]
For naming (I don't have a strong opinion here, but would like to discuss):

* `janitor/expire` (shorter) or
* `janitor/expires` (reminds me of the Expires HTTP header)

**Comment by CookieComputing** [comment]
I would think that that `janitor/expires` is more consistent with the plurals syntax that occurs when including resources (as I found out the hard way), so I'm in favor of `expires`

**Comment by hjacobs** [comment]
@CookieComputing I don't think `expires` should have something to do with plural :smirk: --- for me it's more a question of how to read the annotation as a human:

* `janitor/expire: ..` --> "resource X, please expire at 2019-03-01 13:00Z" (active form)
* `janitor/expires: ..` --> "resource X expires at 2019-03-01 13:00Z" (passive form)

**Comment by SongGithub** [comment]
> Thanks for the PR! I would prefer to use the builtin tooling to parse the timestamp, i.e. use the same logic as here: https://github.com/hjacobs/kube-janitor/blob/master/kube_janitor/janitor.py#L36

yep, good idea, I've changed it over, and then that is one less dependency!

**Comment by SongGithub** [comment]
on the naming, 
I realise `expire` is a verb, and we should really use a noun here. 

how about `expiration`? it is a noun that is a well-known label on food and medicine. I have chosen this after considered:
- `expiry` un-common
- `expiryDate` too long
- `expirationDate` toooo loooong to read

**Comment by hjacobs** [comment]
After thinking about it, I would prefer `expires` as it is consistent with the "Expires" HTTP header (https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21)

**Comment by CookieComputing** [comment]
That thought also crossed my mind: I think `expires` appeals more than `expire`.

**Comment by hjacobs** [comment]
@SongGithub can you change it to `expires`? Otherwise looks good to me!

**Comment by SongGithub** [comment]
@hjacobs , it is done, as seen on the latest commit. Glad we came to a consensus on the naming.

**Comment by SongGithub** [comment]
please merge when you ready :)

**Comment by hjacobs** [comment]
@SongGithub thank you for your contribution :smile:

**Pull request merged**
