### PR TITLE
Dockerise the unit-test phrase 

### PR DESCRIPTION
**Pull request by SongGithub**
This PR will : 
- help to isolate dependencies when executing unit-testing using docker-compose services. So only dep would be 2 common ones: docker, docker-compose. This will not only help build agent to run reliably, but also improve portability for local dev! Devs don't need to install deps such as pytest, pipenv and etc. 
~~- use 'vendoring' technique (a very opinionated point! )to speed up Test and Build process
  -- pro: speed up the process, as it will not go Internet to download packages.
  -- pro: certainty on deps availability. External dependencies could be altered without notice, disappear, or unreachable due to internet issues
  -- con: little burden on Dev. When developers doing local development and they want to add a new Dependency, they would need to manually run supplied docker-compose services to update vendor folder content.~~

### CODE REVIEW

**Comment by hjacobs** [comment]
Hmm, I'm not very happy with the PR I must say:

* as you already mentioned, vendoring is opinionated and I don't really like it (even for go projects we try to avoid this in Zalando by not checking in the vendor folder)
* the `pipenv` dependency is now replaced with docker-compose dependency (not less dependencies, but different)
* overall the PR is pretty complex for something which should be simple

I'm OK with Dockerizing the process, but let's do it in a simple way without introducing new dependencies. As an example, I dockerized the NPM dependency here: https://github.com/hjacobs/kube-ops-view/blob/master/Makefile

**Comment by SongGithub** [comment]
how about running unit tests inside `Dockerfile`. As a result, when CI processes run, dependencies will be installed once, not twice(one when setup the deps for testing on Agent, then setup the same deps again for Docker build). Con is that Docker build process is too long to be an efficient way running tests locally for Devs. 

Alternatively, we could split Dockerfile in 2 parts. The 1st part contains the 1st stage of the original Dockerfile. The built image will be used for both running Tests, and building the next stage. The 2nd part will refer the Docker image name:tag of the 1st one. This way, devs and CI agents can use Docker image from the 1st part of Dockerfile to run tests quickly (once it is built for the 1st time, subsequent builds would have been cached), and the 2nd part can reuse it as well.

**Comment by SongGithub** [comment]
I think the solution described in my previous post's 2nd paragraph is better, as it addresses need for dockerised dev experience. also it keep it relatively simple.

**Comment by SongGithub** [comment]
I have refactored the code, please let me know how you guys think.

**Comment by CookieComputing** [comment]
Can we change the names from `Dockerfile` and `DockerfileII` to be something related to the purpose of the files? E.g. `DockerfileTests` and `DockerfileBuild`, or something along those lines.

**Comment by CookieComputing** [comment]
I'm okay with the approach, but it does mean we have to maintain two separate Dockerfiles. @hjacobs  what do you think?

**Comment by SongGithub** [comment]
> Can we change the names from `Dockerfile` and `DockerfileII` to be something related to the purpose of the files? It would be pretty easy to forget the purposes of the files.

Good point, I have done the renaming.

**Comment by hjacobs** [comment]
`DockerfileII` still seems to be there.

**Comment by SongGithub** [comment]
> `DockerfileII` still seems to be there.

right, I have cleaned them up.

**Comment by hjacobs** [comment]
It does not work as the packages are not installed in the final Docker image:

```
make docker
...
Docker image hjacobs/kube-janitor:0.4-11-g685cb0f can now be used.
docker run -it hjacobs/kube-janitor:0.4-11-g685cb0f --help
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/kube_janitor/__main__.py", line 1, in <module>
    from .main import main  # pragma: no cover
  File "/kube_janitor/main.py", line 7, in <module>
    from kube_janitor.helper import get_kube_api
  File "/kube_janitor/helper.py", line 3, in <module>
    import pykube
ModuleNotFoundError: No module named 'pykube'
```

Maybe we should postpone this whole exercise and keep it as-is?

**Comment by SongGithub** [comment]
Whoops, I found out reason being was that the `pipenv installed` packages are in `~/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/`, and didn't get copied into the last stage.

**Comment by SongGithub** [comment]
I've supplied a fix to the problem, and running `docker run -it hjacobs/kube-janitor:* --help` would work now. 

Once it is working, value will come out that it does make dev/test process highly portable and less relying on dependencies installed on the run-time.

**Pull request closed without merging**
